from app.core.state import CogmateState, LessonSection
from app.core.llm import get_llm_client
import json

async def architect_node(state: CogmateState) -> CogmateState:
    transcript = ' '.join(state['transcript_buffer'])

    # Don't try to build a complex outline until we have enough to work with
    if len(transcript) < 50:
        return {**state, "lesson_outline": state.get("lesson_outline", []), "rewrite_count": state.get("rewrite_count", 0) + 1}

    client = get_llm_client(state.get('model_config'))

    prompt = f"""
    You are an expert Instructional Designer (The Architect Agent).
    Topic: {state['current_topic']}
    Transcript Context: {transcript}
    
    Slide Context: {state.get('slide_context', 'No slide text available.')}
    
    Your task is to structure the learning experience using:
    1. Gagné's Nine Events of Instruction (to sequence the flow).
    2. Bloom's Taxonomy (to ensure cognitive depth: Remember, Understand, Apply, Analyze, Evaluate, Create).
    
    Guidelines:
    - Map the transcript chunks to specific Gagné events.
    - Identify the cognitive level required for each section based on Bloom's.
    - If there are gaps in the explanation, note them in the 'content'.
    
    Return ONLY a JSON list of objects with 'title', 'gagne_event', 'bloom_level', and 'content'.
    Example: [{{"title": "Intro to NN", "gagne_event": "Gain Attention", "bloom_level": "Understand", "content": "..."}}]
    """
    
    try:
        response_text = await client.generate_content(prompt)
        json_str = response_text[response_text.find("["):response_text.rfind("]")+1]
        outline = json.loads(json_str)
    except Exception as e:
        # Fallback
        outline = state.get("lesson_outline", [])
        if not outline:
            outline = [
                {
                    "title": f"Introduction to {state['current_topic']}",
                    "gagne_event": "Gain Attention",
                    "bloom_level": "Understand",
                    "content": "Capturing initial thoughts..."
                }
            ]
    
    return {**state, "lesson_outline": outline, "rewrite_count": state.get("rewrite_count", 0) + 1}

async def highlighter_node(state: CogmateState) -> CogmateState:
    client = get_llm_client(state.get('model_config'))
    
    prompt = f"""
    You are a Pedagogical Highlighter Agent. Your task is to analyze the classroom transcript and extract key learning concepts.
    
    Transcript: {' '.join(state['transcript_buffer'])}
    
    Guidelines:
    1. Identify terms, definitions, and core principles mentioned.
    2. Assign an importance score (1-5) to each concept based on its relevance to the topic.
    3. Filter out filler words or casual conversation.
    
    Return ONLY a JSON list of objects with 'tag' and 'score'.
    Example: [{{"tag": "Backpropagation", "score": 5}}, {{"tag": "Chain Rule", "score": 4}}]
    """
    
    try:
        response_text = await client.generate_content(prompt)
        json_str = response_text[response_text.find("["):response_text.rfind("]")+1]
        concepts = json.loads(json_str)
        tags = [c['tag'] for c in concepts if c.get('score', 0) >= 3]
    except Exception:
        tags = state.get("importance_tags", [])
        
    return {**state, "importance_tags": tags}

async def sim_student_node(state: CogmateState) -> CogmateState:
    client = get_llm_client(state.get('model_config'))
    
    prompt = f"""
    You are a Simulated Student (The Adversarial Evaluator). Your goal is to find flaws in the lesson notes generated by the Architect.
    
    Lesson Notes: {json.dumps(state['lesson_outline'])}
    Original Transcript: {' '.join(state['transcript_buffer'])}
    
    Your Task:
    1. Be skeptical. If a concept is mentioned but not explained clearly, flag it.
    2. Identify "Confusion Points" where a student might get lost.
    3. Look for gaps between the transcript (what was said) and the notes (what was captured).
    4. Rate the overall pedagogical clarity from 0.0 (confusing) to 1.0 (perfect).
    
    Return ONLY a JSON with 'score' and 'confusion_points' (a list of detailed critiques).
    Example: {{"score": 0.65, "confusion_points": ["The transition from step 2 to 3 is too abrupt.", "The term 'Tensor' is used but never defined."]}}
    """
    
    try:
        response_text = await client.generate_content(prompt)
        json_str = response_text[response_text.find("{"):response_text.rfind("}")+1]
        eval_data = json.loads(json_str)
        score = eval_data.get("score", 0.5)
        confusion = eval_data.get("confusion_points", [])
    except Exception:
        score = state.get("eval_score", 0.8)
        confusion = state.get("confusion_points", [])
    
    return {**state, "eval_score": score, "confusion_points": confusion}

async def summarizer_node(state: CogmateState) -> CogmateState:
    if not state['transcript_buffer']:
        return state
        
    client = get_llm_client(state.get('model_config'))
    
    prompt = f"""
    You are a Lecture Summarizer Agent. Provide a comprehensive, high-level summary of the lecture so far.
    Topic: {state['current_topic']}
    Transcript: {' '.join(state['transcript_buffer'])}
    
    Focus on:
    - Main objectives covered
    - Crucial takeaways
    - Summary of the discussion
    
    Format in Markdown.
    """
    
    try:
        summary = await client.generate_content(prompt)
    except Exception:
        summary = state.get("final_summary", "Summary not available.")
        
    return {**state, "final_summary": summary}
