from typing import List, Dict
import io
from pptx import Presentation
from pptx.util import Inches, Pt

def generate_markdown(content: str, title: str = "Cogmate Notes") -> io.BytesIO:
    """
    Generates a Markdown file from the provided content.
    """
    md_content = f"# {title}\n\n{content}"
    buf = io.BytesIO()
    buf.write(md_content.encode("utf-8"))
    buf.seek(0)
    return buf

def generate_pptx(content: str, title: str = "Cogmate Presentation") -> io.BytesIO:
    """
    Generates a PPTX file from the provided content.
    Simple logic: Split content by sections (headings) and create a slide for each.
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by Cogmate AI"

    # Content Slides
    # We'll split by markdown headers if they exist, otherwise by double newlines
    if "\n#" in content:
        sections = content.split("\n#")
    else:
        sections = content.split("\n\n")

    for section in sections:
        if not section.strip():
            continue
            
        lines = section.strip().split("\n")
        section_title = lines[0].replace("#", "").strip()
        section_body = "\n".join(lines[1:]).strip()
        
        if not section_body:
            section_body = section_title
            section_title = "Concept"

        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = section_title
        
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.text = section_body

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf
